language: csharp

dotnet: 6.0.100 
mono:
  - latest
os:
  - linux
script: 
  - dotnet restore nhibernate-studies.sln
  - dotnet build nhibernate-studies.sln
  - dotnet test tests/Tests
  - dotnet test tests/CoreFsTests
  - dotnet test tests/CoreXmlTests
  - dotnet test tests/ClassMapTests
branches:
  only:
    - master
