language: csharp
sudo: false
dist: trusty
dotnet: 2.1.401
mono:
  - latest
os:
  - linux
script: 
  - dotnet restore nhibernate-studies.sln
  - dotnet build nhibernate-studies.sln
  - dotnet test tests/Tests
  - dotnet test tests/CoreXmlTests
  - dotnet test tests/ClassMapTests
branches:
  only:
    - master
