version: 1.0.{build}
configuration: Release
before_build:
  - dotnet restore nhibernate-studies.sln
build_script:
  - dotnet build nhibernate-studies.sln
test_script:
  - dotnet test tests\Tests
  - dotnet test tests\CoreXmlTests
  - dotnet test tests\ClassMapTests
branches:
  only:
    - master
