image: Visual Studio 2022
configuration: Release
install:
  - cmd: choco install dotnetcore-sdk -y
before_build:
  - dotnet restore nhibernate-studies.sln
build_script:
  - dotnet build nhibernate-studies.sln
test_script:
  - dotnet test tests\Tests
  - dotnet test tests\CoreFsTests
  - dotnet test tests\CoreXmlTests
  - dotnet test tests\ClassMapTests
branches:
  only:
    - master
